# -*- coding: utf-8 -*-
"""scRNA-seq_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YezXtankLF1XqaNgB6AMubv-wWQn0rLq

<center> <h1> Анализ данных scRNA-seq
 </h1> </center>



 ---

### Установка библиотек и скачивание данных
"""

pip install scanpy[leiden] scrublet scikit-image

! wget https://datasets.cellxgene.cziscience.com/b9cbe943-ad26-4cac-8798-6453b80834bf.h5ad -O HumanBrain_NuclAccumb.h5ad

import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce
import seaborn as sns
import matplotlib.pyplot as plt

"""Некоторые найстройки ноутбука"""

sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()
sc.settings.set_figure_params(dpi=100, facecolor='white')

"""### Данные



В `scanpy` данные хранятся в т.н. объекте AnnData:

- `adata.X` - таблица с данными (обычно в sparse формате)
- `adata.obs` - метаданные наблюдений (клеток)
- `adata.var` - метаднанные переменных (генов)

Еще есть поля с дополнительными данными (`obsm`, `varm`) и `uns` - unstructured - любые другие полезные данные.

![image.png](attachment:b8c066ab-4d52-4668-80ec-652b9f702c11.png)

### Чтение данных.
"""

adata = sc.read_h5ad('HumanBrain_NuclAccumb.h5ad')

adata

"""> Например, если нужно узнать для каждой клетки - из пациента какого пола она:"""

adata.obs[['sex']].sample(5) # sample это метод pandas df чтобы выбрать случайные строки

# общее число клеток
len(adata.obs.index)

# общее число генов
len(adata.var.index)

#версия схемы
adata.uns

#метаданные клеток
adata.obs

#метаданные генов
adata.var

#число уникальных значений feature_type
a = set(adata.var["feature_type"])
len(a)

#уникальные значения feature_type
a

"""## QC - графики распределений"""

#число каунтов на клетку
sc.pl.violin(
    adata,
    'total_UMIs',
    stripplot = False
)

#число каунтов на ген
sc.pp.calculate_qc_metrics(
    adata, percent_top=None, log1p=False, inplace=True
)

import seaborn as sns
T = adata.var
Ay = sns.violinplot(y=T["total_counts"])

total_counts = adata.var["total_counts"]
adata = adata[:, total_counts < 1e7]

"""## Фильтруем данные: убираем дублеты"""

# # Запускаем Scrublet
sce.pp.scrublet(adata)

# Убираем дубликаты
adata = adata[~adata.obs['predicted_doublet'], :]

# общее число клеток
len(adata.obs.index)

"""## Фильтруем данные: убираем гены и клетки с низким числом каунтов."""

# Задайте эти пороги самостоятельно (исходя из графиков выше и вашего настроения)
min_total_counts_per_gene = 1000
min_total_counts_per_cell = 15000

# Посчитайте суммарное число каунтов на каждую клетку и на каждый ген
cell_counts = adata.obs['total_UMIs']
gene_counts = adata.var['total_counts']

# Делаем фильтрацию
adata = adata[:, gene_counts >= min_total_counts_per_gene]
adata = adata[cell_counts >= min_total_counts_per_cell, :]

# общее число генов
len(adata.var.index)

# общее число клеток
len(adata.obs.index)

"""### Строим mean-var plot"""

def plot_mean_var_plot(adata):
    arr = adata.X.toarray()
    mean_expression = arr.mean(axis=0)
    variance_expression = arr.var(axis=0)


    plt.figure(figsize=(3, 3))
    plt.scatter(mean_expression, variance_expression, alpha=0.5)
    plt.title('Mean-var plot')
    plt.xlabel('Mean gene expression')
    plt.ylabel('Gene expression variance')

plot_mean_var_plot(adata)

"""### Делаем PCA"""

# Считаем PCA
sc.tl.pca(adata)

# Строим scree-plot. Сколько главных компонент логично использовать?
sc.pl.pca_variance_ratio(adata, n_pcs=50)

# Строим PCA
sc.pl.pca(adata, color=['supercluster_term', 'donor_id'], ncols=1)

"""### Gene loadings in PCA"""

def plot_gene_loadings_vs_mean_expression(adata, PC=1):
    mean_expression = np.array(adata.X.mean(axis=0)).flatten()
    pca_loadings = adata.varm['PCs'][:, PC-1]

    plt.figure(figsize=(3, 3))
    plt.scatter(mean_expression, pca_loadings, alpha=0.5)
    plt.title(f'PCA Loadings (PC{PC}) vs. Mean Gene Expression')
    plt.xlabel(f'Mean Gene Expression')
    plt.ylabel(f'PCA Loadings (PC{PC})')
    plt.grid(True)
    plt.show()

plot_gene_loadings_vs_mean_expression(adata) # у меня получилось так, но у вас может быть по-другому

"""### Нормализация данных"""

# ваш код (см. вопросы)
sc.pp.log1p(adata)

plot_gene_loadings_vs_mean_expression(adata)

"""### Mean-var plot и PCA gene loadings на нормализованных данных"""

# ваш код (см. вопросы)
plot_mean_var_plot(adata)

plot_gene_loadings_vs_mean_expression(adata)

"""### UMAP"""

# Рассчитываем UMAP
sc.pp.neighbors(adata) # помним, для UMAP нужен kNN-graph!
sc.tl.umap(adata)

sc.pl.umap(adata, color=['supercluster_term', 'donor_id'], ncols=1)

"""### Экспрессия генов"""

selected_genes = ["NCAM1", "GRIN2B", "APOE", "DRD2"]
dp = sc.pl.dotplot(adata, selected_genes,
                   groupby="cell_type", gene_symbols='Gene',
                   return_fig=True)

# Дополнительные настройки графиков (чтобы было красиво)
ax = dp.get_axes()['mainplot_ax']
ax.tick_params(axis='x', labelrotation=45)
for label in ax.get_xticklabels():
    label.set_ha('right')  # Horizontal alignment